# -*- coding: utf-8 -*-
"""LocalHost10thFinal

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BVYmw-3Lbw4_KwA4e0JT48KoTbIVNDOg
"""

!pip install pyngrok
!pip install flask

from flask import Flask
from pyngrok import ngrok

ngrok.set_auth_token("2AbuShA0JmI3FykUuabqqnCYu1I_9YDA4bUvaXELaJpn2z2r")
public_url = ngrok.connect(5000).public_url

port_no = 6969
from flask import Flask, render_template, request
import pandas as pd
import pickle
import os

def getResults(X_test):
  try: 
      with open('model_pickle', 'rb') as f:
          mp = pickle.load(f)
      
      X = X_test.copy()
      X.drop(['usn'],axis=1, inplace=True)
      grades = mp.predict(X)
      gradesDF = pd.DataFrame(grades, columns = ['Grades'])
      d = {0: 'Grade C', 1: 'Grade B', 2: 'Grade A'}
      gradesDF['Grades'] = gradesDF['Grades'].map(d)
      X_test['Grades'] = gradesDF
      res = X_test[['usn', 'Grades']]
      return res.to_html(header="true", table_id="table")
  except:
      return "<h1>The file is not valid</h1>"

app = Flask(__name__)
ngrok.set_auth_token("2AbuShA0JmI3FykUuabqqnCYu1I_9YDA4bUvaXELaJpn2z2r")
public_url = ngrok.connect(port_no).public_url
@app.route("/", methods=["GET"])
def getHome():
  return render_template("index.html")

@app.route("/", methods=["POST"])
def predict():
  file = request.files['csvfile']
  if not os.path.isdir('static'):
      os.mkdir('static')
  filepath = os.path.join('static', file.filename)
  file.save(filepath)

  df = pd.read_csv(filepath)
  results = getResults(df)
  return results  

print("The Global url is:",public_url)
app.run(port=port_no)

